package moe.quill.Crafting.Items.MaterialManager.StratumMaterials;

public enum StratumMaterial {
    //SHARDS
    SHARD_COMMON,
    SHARD_UNCOMMON,
    SHARD_RARE,
    SHARD_EPIC,
    SHARD_LEGENDARY,

    //FRAGMENTS
    FRAGMENT_COMMON,
    FRAGMENT_UNCOMMON,
    FRAGMENT_RARE,
    FRAGMENT_EPIC,
    FRAGMENT_LEGENDARY,

    //GEODES
    GEODE_COMMON,
    GEODE_UNCOMMON,
    GEODE_RARE,
    GEODE_EPIC,
    GEODE_LEGENDARY,

    //BATTLEAXES
    BATTLEAXE_WOODEN,
    BATTLEAXE_STONE,
    BATTLEAXE_IRON,
    BATTLEAXE_GOLDEN,
    BATTLEAXE_DIAMOND,
    BATTLEAXE_NETHERITE,

    //Scythes
    SCYTHE_WOODEN,
    SCYTHE_STONE,
    SCYTHE_IRON,
    SCYTHE_GOLDEN,
    SCYTHE_DIAMOND,
    SCYTHE_NETHERITE,

    //DAGGERS
    DAGGER_WOODEN,
    DAGGER_STONE,
    DAGGER_IRON,
    DAGGER_GOLDEN,
    DAGGER_DIAMOND,
    DAGGER_NETHERITE,

    //CUTLASSES
    CUTLASS_WOODEN,
    CUTLASS_STONE,
    CUTLASS_IRON,
    CUTLASS_GOLDEN,
    CUTLASS_DIAMOND,
    CUTLASS_NETHERITE,

    //CHESTS
    CHEST_COMMON,
    CHEST_UNCOMMON,
    CHEST_RARE,
    CHEST_EPIC,
    CHEST_LEGENDARY,

    //TRINKET_BAGS
    TRINKET_BAG_SMALL,
    TRINKET_BAG_MEDIUM,
    TRINKET_BAG_LARGE,

    //HELMETS
    HELMET_LEATHER_LIGHT,
    HELMET_GOLDEN_LIGHT,
    HELMET_CHAIN_LIGHT,
    HELMET_IRON_LIGHT,
    HELMET_DIAMOND_LIGHT,
    HELMET_NETHERITE_LIGHT,
    HELMET_LEATHER_HEAVY,
    HELMET_GOLDEN_HEAVY,
    HELMET_CHAIN_HEAVY,
    HELMET_IRON_HEAVY,
    HELMET_DIAMOND_HEAVY,
    HELMET_NETHERITE_HEAVY,
    HELMET_LEATHER_JUG,
    HELMET_GOLDEN_JUG,
    HELMET_CHAIN_JUG,
    HELMET_IRON_JUG,
    HELMET_DIAMOND_JUG,
    HELMET_NETHERITE_JUG,

    //CHESTPLATES
    CHESTPLATE_LEATHER_LIGHT,
    CHESTPLATE_GOLDEN_LIGHT,
    CHESTPLATE_CHAIN_LIGHT,
    CHESTPLATE_IRON_LIGHT,
    CHESTPLATE_DIAMOND_LIGHT,
    CHESTPLATE_NETHERITE_LIGHT,
    CHESTPLATE_LEATHER_HEAVY,
    CHESTPLATE_GOLDEN_HEAVY,
    CHESTPLATE_CHAIN_HEAVY,
    CHESTPLATE_IRON_HEAVY,
    CHESTPLATE_DIAMOND_HEAVY,
    CHESTPLATE_NETHERITE_HEAVY,
    CHESTPLATE_LEATHER_JUG,
    CHESTPLATE_GOLDEN_JUG,
    CHESTPLATE_CHAIN_JUG,
    CHESTPLATE_IRON_JUG,
    CHESTPLATE_DIAMOND_JUG,
    CHESTPLATE_NETHERITE_JUG,

    //LEGGINGS
    LEGGINGS_LEATHER_LIGHT,
    LEGGINGS_GOLDEN_LIGHT,
    LEGGINGS_CHAIN_LIGHT,
    LEGGINGS_IRON_LIGHT,
    LEGGINGS_DIAMOND_LIGHT,
    LEGGINGS_NETHERITE_LIGHT,
    LEGGINGS_LEATHER_HEAVY,
    LEGGINGS_GOLDEN_HEAVY,
    LEGGINGS_CHAIN_HEAVY,
    LEGGINGS_IRON_HEAVY,
    LEGGINGS_DIAMOND_HEAVY,
    LEGGINGS_NETHERITE_HEAVY,
    LEGGINGS_LEATHER_JUG,
    LEGGINGS_GOLDEN_JUG,
    LEGGINGS_CHAIN_JUG,
    LEGGINGS_IRON_JUG,
    LEGGINGS_DIAMOND_JUG,
    LEGGINGS_NETHERITE_JUG,

    //BOOTS
    BOOTS_LEATHER_LIGHT,
    BOOTS_GOLDEN_LIGHT,
    BOOTS_CHAIN_LIGHT,
    BOOTS_IRON_LIGHT,
    BOOTS_DIAMOND_LIGHT,
    BOOTS_NETHERITE_LIGHT,
    BOOTS_LEATHER_HEAVY,
    BOOTS_GOLDEN_HEAVY,
    BOOTS_CHAIN_HEAVY,
    BOOTS_IRON_HEAVY,
    BOOTS_DIAMOND_HEAVY,
    BOOTS_NETHERITE_HEAVY,
    BOOTS_LEATHER_JUG,
    BOOTS_GOLDEN_JUG,
    BOOTS_CHAIN_JUG,
    BOOTS_IRON_JUG,
    BOOTS_DIAMOND_JUG,
    BOOTS_NETHERITE_JUG,

    //ICE PICKS
    ICEPICK_WOODEN,
    ICEPICK_STONE,
    ICEPICK_IRON,
    ICEPICK_GOLDEN,
    ICEPICK_DIAMOND,
    ICEPICK_NETHERITE,

    //HAMMERS
    HAMMER_WOODEN,
    HAMMER_STONE,
    HAMMER_IRON,
    HAMMER_GOLDEN,
    HAMMER_DIAMOND,
    HAMMER_NETHERITE,

    //ADD THE GRAPPLING HOOK
    GRAPPLING_HOOK,

    //TRINKET BAGS
    SMALL_TRINKET_BAG,
    MEDIUM_TRINKET_BAG,
    LARGE_TRINKET_BAG,

    //Inventory item Helper
    BLOCKADE,
}
