name: stratumsurvival
version: ${project.version}
main: tech.quilldev.stratumsurvival
api-version: 1.16

commands:
  dev:
    usage: /<command>
    permission: stratumsurvival.developer.dev
  devtool:
    usage: /<command>
    permission: stratumsurvival.developer.dev
  playinggod:
    usage: /<command>
    permission: stratumsurvival.developer.playinggod
  createrandomitem:
    usage: /<command>
    permission: stratumsurvival.developer.dev
