name: StratumSurvival
version: ${project.version}
main: tech.quilldev.StratumSurvival
api-version: 1.16

commands:
  dev:
    usage: /<command>
    permission: stratumsurvival.developer.dev
  devtool:
    usage: /<command>
  generateitem:
    usage: /<command> <level>
  obfuscate:
    usage: /<command>
  deobfuscate:
    usage: /<command>
  spawnnpc:
    usage: /<command> <type>
  reroll:
    usage: /<command>
  addnpcline:
    usage: /<command> <npcname> <line>
  spawnchatnpc:
    usage: /<command> <npcname>
