name: StratumSurvival
version: ${project.version}
main: tech.quilldev.StratumSurvival
api-version: 1.16

commands:
  dev:
    usage: /<command>
    permission: stratumsurvival.developer.dev
  generateitem:
    usage: /<command> <level>
  obfuscate:
    usage: /<command>
  deobfuscate:
    usage: /<command>
  spawnnpc:
    usage: /<command> <type>
