name: StratumSurvival
version: ${project.version}
main: moe.quill.stratumsurvival.StratumSurvival
api-version: 1.16
depend: [StratumCommon]
commands:
  dev:
    usage: /<command>
    permission: stratumsurvival.developer.dev
  devtool:
    usage: /<command>
    permission: stratumsurvival.developer.devtool

  #Item Permissions
  generateitem:
    usage: /<command> <WEAPON_TYPE> <AMT>
    permission: stratumsurvival.items.generateitem
  obfuscate:
    usage: /<command>
    permission: stratumsurvival.items.obfuscate
  deobfuscate:
    usage: /<command>
    permission: stratumsurvival.items.deobfuscate
  reroll:
    usage: /<command>
    permission: stratumsurvival.items.reroll
  stratumgive:
    usage: /<command> <itemtype>
    permission: stratumsurvival.items.give
  listkeys:
    usage: /<command>
    permission: stratumsurvival.items.listkeys

  #Bosses
  worldbosstp:
    usage: /<command>
    permission: stratumsurvival.bosses.tp
  spawnworldboss:
    usage: /<command>
    permission: stratumsurvival.bosses.summon
  spawnworldbossdelayed:
    usage: /<command>
    permission: stratumsurvival.bosses.summon

  #Custom Enemies
  spawnenemy:
    usage: /<command>
    permission: stratumsurvival.enemies.spawnenemy

  #Test COmmand
  test:
    usage: /<command>
    permission: stratumsurvival.dev.test