package moe.quill.Crafting;

public enum RecipeKey {
    //BATTLEAXE RECIPES
    RECIPE_BATTLEAXE_WOODEN,
    RECIPE_BATTLEAXE_STONE,
    RECIPE_BATTLEAXE_GOLDEN,
    RECIPE_BATTLEAXE_IRON,
    RECIPE_BATTLEAXE_DIAMOND,
    RECIPE_BATTLEAXE_NETHERITE,

    //DAGGER RECIPES
    RECIPE_DAGGER_WOODEN,
    RECIPE_DAGGER_STONE,
    RECIPE_DAGGER_GOLDEN,
    RECIPE_DAGGER_IRON,
    RECIPE_DAGGER_DIAMOND,
    RECIPE_DAGGER_NETHERITE,

    //SCYTHE RECIPES
    RECIPE_SCYTHE_WOODEN,
    RECIPE_SCYTHE_STONE,
    RECIPE_SCYTHE_GOLDEN,
    RECIPE_SCYTHE_IRON,
    RECIPE_SCYTHE_DIAMOND,
    RECIPE_SCYTHE_NETHERITE,

    //CUTLASS RECIPES
    RECIPE_CUTLASS_WOODEN,
    RECIPE_CUTLASS_STONE,
    RECIPE_CUTLASS_GOLDEN,
    RECIPE_CUTLASS_IRON,
    RECIPE_CUTLASS_DIAMOND,
    RECIPE_CUTLASS_NETHERITE,
    //Shard Recipes
    SHARD_COMMON_TO_UNCOMMON,
    SHARD_UNCOMMON_TO_RARE,
    SHARD_RARE_TO_EPIC,
    SHARD_EPIC_TO_LEGENDARY,

    //Fragment Recipes
    FRAGMENT_COMMON_TO_UNCOMMON,
    FRAGMENT_UNCOMMON_TO_RARE,
    FRAGMENT_RARE_TO_EPIC,
    FRAGMENT_EPIC_TO_LEGENDARY,

    //Frag To Shard Recipes
    FRAG_TO_SHARD_COMMON,
    FRAG_TO_SHARD_UNCOMMON,
    FRAG_TO_SHARD_RARE,
    FRAG_TO_SHARD_EPIC,
    FRAG_TO_SHARD_LEGENDARY,

    //TODO: JEFF FIX THIS FOR THE LOVE OF GOD
    //HELMETS
    RECIPE_HELMET_LEATHER_LIGHT,
    RECIPE_HELMET_GOLDEN_LIGHT,
    RECIPE_HELMET_CHAIN_LIGHT,
    RECIPE_HELMET_IRON_LIGHT,
    RECIPE_HELMET_DIAMOND_LIGHT,
    RECIPE_HELMET_NETHERITE_LIGHT,
    RECIPE_HELMET_LEATHER_HEAVY,
    RECIPE_HELMET_GOLDEN_HEAVY,
    RECIPE_HELMET_CHAIN_HEAVY,
    RECIPE_HELMET_IRON_HEAVY,
    RECIPE_HELMET_DIAMOND_HEAVY,
    RECIPE_HELMET_NETHERITE_HEAVY,
    RECIPE_HELMET_LEATHER_JUG,
    RECIPE_HELMET_GOLDEN_JUG,
    RECIPE_HELMET_CHAIN_JUG,
    RECIPE_HELMET_IRON_JUG,
    RECIPE_HELMET_DIAMOND_JUG,
    RECIPE_HELMET_NETHERITE_JUG,

    //CHESTPLATES
    RECIPE_CHESTPLATE_LEATHER_LIGHT,
    RECIPE_CHESTPLATE_GOLDEN_LIGHT,
    RECIPE_CHESTPLATE_CHAIN_LIGHT,
    RECIPE_CHESTPLATE_IRON_LIGHT,
    RECIPE_CHESTPLATE_DIAMOND_LIGHT,
    RECIPE_CHESTPLATE_NETHERITE_LIGHT,
    RECIPE_CHESTPLATE_LEATHER_HEAVY,
    RECIPE_CHESTPLATE_GOLDEN_HEAVY,
    RECIPE_CHESTPLATE_CHAIN_HEAVY,
    RECIPE_CHESTPLATE_IRON_HEAVY,
    RECIPE_CHESTPLATE_DIAMOND_HEAVY,
    RECIPE_CHESTPLATE_NETHERITE_HEAVY,
    RECIPE_CHESTPLATE_LEATHER_JUG,
    RECIPE_CHESTPLATE_GOLDEN_JUG,
    RECIPE_CHESTPLATE_CHAIN_JUG,
    RECIPE_CHESTPLATE_IRON_JUG,
    RECIPE_CHESTPLATE_DIAMOND_JUG,
    RECIPE_CHESTPLATE_NETHERITE_JUG,

    //LEGGINGS
    RECIPE_LEGGINGS_LEATHER_LIGHT,
    RECIPE_LEGGINGS_GOLDEN_LIGHT,
    RECIPE_LEGGINGS_CHAIN_LIGHT,
    RECIPE_LEGGINGS_IRON_LIGHT,
    RECIPE_LEGGINGS_DIAMOND_LIGHT,
    RECIPE_LEGGINGS_NETHERITE_LIGHT,
    RECIPE_LEGGINGS_LEATHER_HEAVY,
    RECIPE_LEGGINGS_GOLDEN_HEAVY,
    RECIPE_LEGGINGS_CHAIN_HEAVY,
    RECIPE_LEGGINGS_IRON_HEAVY,
    RECIPE_LEGGINGS_DIAMOND_HEAVY,
    RECIPE_LEGGINGS_NETHERITE_HEAVY,
    RECIPE_LEGGINGS_LEATHER_JUG,
    RECIPE_LEGGINGS_GOLDEN_JUG,
    RECIPE_LEGGINGS_CHAIN_JUG,
    RECIPE_LEGGINGS_IRON_JUG,
    RECIPE_LEGGINGS_DIAMOND_JUG,
    RECIPE_LEGGINGS_NETHERITE_JUG,

    //BOOTS
    RECIPE_BOOTS_LEATHER_LIGHT,
    RECIPE_BOOTS_GOLDEN_LIGHT,
    RECIPE_BOOTS_CHAIN_LIGHT,
    RECIPE_BOOTS_IRON_LIGHT,
    RECIPE_BOOTS_DIAMOND_LIGHT,
    RECIPE_BOOTS_NETHERITE_LIGHT,
    RECIPE_BOOTS_LEATHER_HEAVY,
    RECIPE_BOOTS_GOLDEN_HEAVY,
    RECIPE_BOOTS_CHAIN_HEAVY,
    RECIPE_BOOTS_IRON_HEAVY,
    RECIPE_BOOTS_DIAMOND_HEAVY,
    RECIPE_BOOTS_NETHERITE_HEAVY,
    RECIPE_BOOTS_LEATHER_JUG,
    RECIPE_BOOTS_GOLDEN_JUG,
    RECIPE_BOOTS_CHAIN_JUG,
    RECIPE_BOOTS_IRON_JUG,
    RECIPE_BOOTS_DIAMOND_JUG,
    RECIPE_BOOTS_NETHERITE_JUG,

    //GRAPPLING HOOK RECIPE
    RECIPE_GRAPPLING_HOOK,


}
