package moe.quill.Crafting;

public enum RecipeKey {
    //BATTLEAXE RECIPES
    RECIPE_BATTLEAXE_WOODEN,
    RECIPE_BATTLEAXE_STONE,
    RECIPE_BATTLEAXE_GOLDEN,
    RECIPE_BATTLEAXE_IRON,
    RECIPE_BATTLEAXE_DIAMOND,
    RECIPE_BATTLEAXE_NETHERITE,

    //DAGGER RECIPES
    RECIPE_DAGGER_WOODEN,
    RECIPE_DAGGER_STONE,
    RECIPE_DAGGER_GOLDEN,
    RECIPE_DAGGER_IRON,
    RECIPE_DAGGER_DIAMOND,
    RECIPE_DAGGER_NETHERITE,

    //Shard Recipes
    SHARD_COMMON_TO_UNCOMMON,
    SHARD_UNCOMMON_TO_RARE,
    SHARD_RARE_TO_EPIC,
    SHARD_EPIC_TO_LEGENDARY,

    //Fragment Recipes
    FRAGMENT_COMMON_TO_UNCOMMON,
    FRAGMENT_UNCOMMON_TO_RARE,
    FRAGMENT_RARE_TO_EPIC,
    FRAGMENT_EPIC_TO_LEGENDARY,

    //Frag To Shard Recipes
    FRAG_TO_SHARD_COMMON,
    FRAG_TO_SHARD_UNCOMMON,
    FRAG_TO_SHARD_RARE,
    FRAG_TO_SHARD_EPIC,
    FRAG_TO_SHARD_LEGENDARY,

    //HELMETS
    RECIPIE_HELMET_LEATHER_LIGHT,
    RECIPIE_HELMET_LEATHER_HEAVY,
    RECIPIE_HELMET_GOLDEN_LIGHT,
    RECIPIE_HELMET_GOLDEN_HEAVY,
    RECIPIE_HELMET_CHAIN_LIGHT,
    RECIPIE_HELMET_CHAIN_HEAVY,
    RECIPIE_HELMET_IRON_LIGHT,
    RECIPIE_HELMET_IRON_HEAVY,
    RECIPIE_HELMET_DIAMOND_LIGHT,
    RECIPIE_HELMET_DIAMOND_HEAVY,
    RECIPIE_HELMET_NETHERITE_LIGHT,
    RECIPIE_HELMET_NETHERITE_HEAVY,

    //CHESTPLATES
    RECIPIE_CHESTPLATE_LEATHER_LIGHT,
    RECIPIE_CHESTPLATE_LEATHER_HEAVY,
    RECIPIE_CHESTPLATE_GOLDEN_LIGHT,
    RECIPIE_CHESTPLATE_GOLDEN_HEAVY,
    RECIPIE_CHESTPLATE_CHAIN_LIGHT,
    RECIPIE_CHESTPLATE_CHAIN_HEAVY,
    RECIPIE_CHESTPLATE_IRON_LIGHT,
    RECIPIE_CHESTPLATE_IRON_HEAVY,
    RECIPIE_CHESTPLATE_DIAMOND_LIGHT,
    RECIPIE_CHESTPLATE_DIAMOND_HEAVY,
    RECIPIE_CHESTPLATE_NETHERITE_LIGHT,
    RECIPIE_CHESTPLATE_NETHERITE_HEAVY,

    //LEGGINGS
    RECIPIE_LEGGINGS_LEATHER_LIGHT,
    RECIPIE_LEGGINGS_LEATHER_HEAVY,
    RECIPIE_LEGGINGS_GOLDEN_LIGHT,
    RECIPIE_LEGGINGS_GOLDEN_HEAVY,
    RECIPIE_LEGGINGS_CHAIN_LIGHT,
    RECIPIE_LEGGINGS_CHAIN_HEAVY,
    RECIPIE_LEGGINGS_IRON_LIGHT,
    RECIPIE_LEGGINGS_IRON_HEAVY,
    RECIPIE_LEGGINGS_DIAMOND_LIGHT,
    RECIPIE_LEGGINGS_DIAMOND_HEAVY,
    RECIPIE_LEGGINGS_NETHERITE_LIGHT,
    RECIPIE_LEGGINGS_NETHERITE_HEAVY,

    //BOOTS
    RECIPIE_BOOTS_LEATHER_LIGHT,
    RECIPIE_BOOTS_LEATHER_HEAVY,
    RECIPIE_BOOTS_GOLDEN_LIGHT,
    RECIPIE_BOOTS_GOLDEN_HEAVY,
    RECIPIE_BOOTS_CHAIN_LIGHT,
    RECIPIE_BOOTS_CHAIN_HEAVY,
    RECIPIE_BOOTS_IRON_LIGHT,
    RECIPIE_BOOTS_IRON_HEAVY,
    RECIPIE_BOOTS_DIAMOND_LIGHT,
    RECIPIE_BOOTS_DIAMOND_HEAVY,
    RECIPIE_BOOTS_NETHERITE_LIGHT,
    RECIPIE_BOOTS_NETHERITE_HEAVY,


}
