package moe.quill.Crafting;

public enum RecipeKey {
    //BATTLEAXE RECIPES
    RECIPE_BATTLEAXE_WOODEN,
    RECIPE_BATTLEAXE_STONE,
    RECIPE_BATTLEAXE_GOLDEN,
    RECIPE_BATTLEAXE_IRON,
    RECIPE_BATTLEAXE_DIAMOND,
    RECIPE_BATTLEAXE_NETHERITE,

    //DAGGER RECIPES
    RECIPE_DAGGER_WOODEN,
    RECIPE_DAGGER_STONE,
    RECIPE_DAGGER_GOLDEN,
    RECIPE_DAGGER_IRON,
    RECIPE_DAGGER_DIAMOND,
    RECIPE_DAGGER_NETHERITE,

    //Shard Recipes
    SHARD_COMMON_TO_UNCOMMON,
    SHARD_UNCOMMON_TO_RARE,
    SHARD_RARE_TO_EPIC,
    SHARD_EPIC_TO_LEGENDARY,

    //Fragment Recipes
    FRAGMENT_COMMON_TO_UNCOMMON,
    FRAGMENT_UNCOMMON_TO_RARE,
    FRAGMENT_RARE_TO_EPIC,
    FRAGMENT_EPIC_TO_LEGENDARY,

    //Frag To Shard Recipes
    FRAG_TO_SHARD_COMMON,
    FRAG_TO_SHARD_UNCOMMON,
    FRAG_TO_SHARD_RARE,
    FRAG_TO_SHARD_EPIC,
    FRAG_TO_SHARD_LEGENDARY

}
