package tech.quilldev.CustomItems.MaterialManager.StratumMaterials;

public enum StratumMaterial {
    //SHARDS
    SHARD_COMMON,
    SHARD_UNCOMMON,
    SHARD_RARE,
    SHARD_EPIC,
    SHARD_LEGENDARY,

    //FRAGMENTS
    FRAGMENT_COMMON,
    FRAGMENT_UNCOMMON,
    FRAGMENT_RARE,
    FRAGMENT_EPIC,
    FRAGMENT_LEGENDARY,

    //GEODES
    GEODE_COMMON,
    GEODE_UNCOMMON,
    GEODE_RARE,
    GEODE_EPIC,
    GEODE_LEGENDARY,

    //BATTLEAXES
    BATTLEAXE_WOODEN,
    BATTLEAXE_STONE,
    BATTLEAXE_IRON,
    BATTLEAXE_GOLDEN,
    BATTLEAXE_DIAMOND,
    BATTLEAXE_NETHERITE,

    //Scythes
    SCYTHE_WOODEN,
    SCYTHE_STONE,
    SCYTHE_IRON,
    SCYTHE_GOLDEN,
    SCYTHE_DIAMOND,
    SCYTHE_NETHERITE,

    //DAGGERS
    DAGGER_WOODEN,
    DAGGER_STONE,
    DAGGER_IRON,
    DAGGER_GOLDEN,
    DAGGER_DIAMOND,
    DAGGER_NETHERITE,

    //CUtlasses
    CUTLASS_WOODEN,
    CUTLASS_STONE,
    CUTLASS_IRON,
    CUTLASS_GOLDEN,
    CUTLASS_DIAMOND,
    CUTLASS_NETHERITE,

    //CHESTS
    CHEST_COMMON,
    CHEST_UNCOMMON,
    CHEST_RARE,
    CHEST_EPIC,
    CHEST_LEGENDARY
    ;
}
