package tech.quilldev.Crafting;

public enum StratumMaterial {
    SHARD_COMMON,
    SHARD_UNCOMMON,
    SHARD_RARE,
    SHARD_EPIC,
    SHARD_LEGENDARY,
    GEODE_COMMON,
    GEODE_UNCOMMON,
    GEODE_RARE,
    GEODE_EPIC,
    GEODE_LEGENDARY,
    BATTLEAXE_WOODEN,
    BATTLEAXE_STONE,
    BATTLEAXE_IRON,
    BATTLEAXE_GOLDEN,
    BATTLEAXE_DIAMOND,
    BATTLEAXE_NETHERITE,
    DAGGER_WOODEN,
    DAGGER_STONE,
    DAGGER_IRON,
    DAGGER_GOLDEN,
    DAGGER_DIAMOND,
    DAGGER_NETHERITE;
}
