package tech.quilldev.Crafting;

public enum StratumMaterial {
    SHARD_COMMON,
    SHARD_UNCOMMON,
    SHARD_RARE,
    SHARD_EPIC,
    SHARD_LEGENDARY,
    BATTLEAXE_WOODEN,
    BATTLEAXE_STONE,
    BATTLEAXE_IRON,
    BATTLEAXE_GOLDEN,
    BATTLEAXE_DIAMOND,
    BATTLEAXE_NETHERITE,
    ;
}
